name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  pypi:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/project/uedition-editor

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.11

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Base Dependencies
        run: |
          sudo apt-get install -y python3-venv
          sudo apt-get remove -y python3-packaging
          sudo pip install hatch

      - name: Build the package
        run: |
          hatch build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
