name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  pypi:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/project/uedition-editor

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.11

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Base Dependencies
        run: |
          sudo apt-get install -y python3-venv
          sudo apt-get remove -y python3-packaging
          sudo pip install hatch

      - name: Build the package
        run: |
          hatch build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.11

      - uses: actions/setup-node@v4
        with:
          node-version: |
            20

      - name: Add .local path
        run: |
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          echo "PIPX_HOME=$HOME/.local/pipx" >> $GITHUB_ENV
          echo "PIPX_BIN_DIR=$HOME/.local/bin" >> $GITHUB_ENV

      - name: Install Base Dependencies
        run: |
          sudo apt-get install python3-venv pipx qemu-user-static
          pipx install hatch

      - name: Strip version prefix
        id: strip-prefix
        run: |
          VERSION=`hatch version`
          echo "result=$VERSION" >> "$GITHUB_OUTPUT"

      - uses: winterjung/split@v2
        id: split
        with:
          msg: ${{ steps.strip-prefix.outputs.result }}
          separator: "."

      - name: Build the python package
        run: |
          hatch build

      - name: Build the container image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
            image: uedition/uedition-editor
            tags: ${{ steps.strip-prefix.outputs.result }}
            containerfiles: |
              ./Containerfile
            platforms: linux/arm64/v8,linux/amd64

      - name: Push the container image to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
