name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  functional-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Add .local path
        run: |
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          echo "PIPX_HOME=$HOME/.local/pipx" >> $GITHUB_ENV
          echo "PIPX_BIN_DIR=$HOME/.local/bin" >> $GITHUB_ENV

      - name: Install Base Dependencies
        run: |
          sudo apt-get install python3-venv pipx
          pipx install hatch
          cd uedition_editor/frontend
          npm install

      - name: Build the Frontend
        run: |
          cd uedition_editor/frontend
          npm run build

      - name: Run Tests
        run: |
          hatch run cov

  e2e-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Add .local path
        run: |
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          echo "PIPX_HOME=$HOME/.local/pipx" >> $GITHUB_ENV
          echo "PIPX_BIN_DIR=$HOME/.local/bin" >> $GITHUB_ENV

      - name: Install Base Dependencies
        run: |
          sudo apt-get install python3-venv pipx
          pipx install hatch
          cd uedition_editor/frontend
          npm install
          cd ../../tests/e2e_tests
          npm install
          npx playwright install --with-deps

      - name: Build the Frontend
        run: |
          cd uedition_editor/frontend
          npm run build

      - name: Run the Tests
        run: |
          hatch run e2e-tests
